apiVersion: sql.gcp.upbound.io/v1beta1
kind: DatabaseInstance
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1beta1/databaseinstance
  labels:
    testing.upbound.io/example-name: example_instance
  name: example-instance-random
spec:
  forProvider:
    databaseVersion: MYSQL_5_7
    deletionProtection: false
    region: us-central1
    settings:
      - diskSize: 20
        tier: db-f1-micro
  writeConnectionSecretToRef:
    name: example-sql-db-instance-secret
    namespace: crossplane-system
~                                   
